module.exports = {
    spring: [
        'apples',
        'apricots',
        'asparagus',
        'avocado',
        'bananas',
        'broccoli',
        'cabbage',
        'carrots',
        'celery',
        'collard greens',
        'garlic',
        'greens',
        'lettuce',
        'mushrooms',
        'onions',
        'peas',
        'pineapple',
        'radishes',
        'rhubarb',
        'spinach',
        'strawberries',
        'swiss chard',
        'turnips',
    ],
    summer: [
        'apples',
        'apricots',
        'avocado',
        'bananas',
        'beets',
        'bell peppers',
        'blackberries',
        'blueberries',
        'carrots',
        'cantaloupe',
        'celery',
        'cherries',
        'collard greens',
        'corn',
        'cucumbers',
        'eggplant',
        'garlic',
        'green',
        'honeydew',
        'jalapeños',
        'kiwifruit',
        'lima beans',
        'mangos',
        'melons',
        'nectarines'
    ],
    fall: [
        'apples',
        'bananas',
        'beets',
        'bell peppers',
        'broccoli',
        'brussels sprouts',
        'cabbage',
        'carrots',
        'cauliflower',
        'celery',
        'collard greens',
        'cranberries',
        'garlic',
        'ginger',
        'grapes',
        'greens',
        'green beans',
        'kale',
        'lettuce',
        'mangos',
        'mushrooms',
        'onions',
        'parsnips'
    ],
    winter: [
        'apples',
        'avocadoes',
        'bananas',
        'beets',
        'brussels sprouts',
        'cabbage',
        'carrots',
        'celery',
        'grapefruit',
        'kale',
        'leek',
        'lemons',
        'onions',
        'oranges',
        'parsnips',
        'pears',
        'pineapples',
        'potatoes',
        'pumpkins',
        'rutabagas',
        'sweet potatoes',
        'turnips',
        'winter squash'
    ]
};
